/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Downloads;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Files;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Folders;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Groups;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Nodes;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Policies;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Settings;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Shares;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Tags;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Tasks;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Users;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Webdavs;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FOLDER_ID = Internal.createIndex(DSL.name("folder_id"), Files.FILES, new OrderField[] { Files.FILES.FOLDER_ID }, false);
    public static final Index IDX_DOWNLOADS_DELETED_AT = Internal.createIndex(DSL.name("idx_downloads_deleted_at"), Downloads.DOWNLOADS, new OrderField[] { Downloads.DOWNLOADS.DELETED_AT }, false);
    public static final Index IDX_FILES_DELETED_AT = Internal.createIndex(DSL.name("idx_files_deleted_at"), Files.FILES, new OrderField[] { Files.FILES.DELETED_AT }, false);
    public static final Index IDX_FOLDERS_DELETED_AT = Internal.createIndex(DSL.name("idx_folders_deleted_at"), Folders.FOLDERS, new OrderField[] { Folders.FOLDERS.DELETED_AT }, false);
    public static final Index IDX_GROUPS_DELETED_AT = Internal.createIndex(DSL.name("idx_groups_deleted_at"), Groups.GROUPS, new OrderField[] { Groups.GROUPS.DELETED_AT }, false);
    public static final Index IDX_NODES_DELETED_AT = Internal.createIndex(DSL.name("idx_nodes_deleted_at"), Nodes.NODES, new OrderField[] { Nodes.NODES.DELETED_AT }, false);
    public static final Index IDX_ONLY_ONE = Internal.createIndex(DSL.name("idx_only_one"), Files.FILES, new OrderField[] { Files.FILES.NAME, Files.FILES.USER_ID, Files.FILES.FOLDER_ID }, true);
    public static final Index IDX_ONLY_ONE_NAME = Internal.createIndex(DSL.name("idx_only_one_name"), Folders.FOLDERS, new OrderField[] { Folders.FOLDERS.NAME, Folders.FOLDERS.PARENT_ID }, true);
    public static final Index IDX_POLICIES_DELETED_AT = Internal.createIndex(DSL.name("idx_policies_deleted_at"), Policies.POLICIES, new OrderField[] { Policies.POLICIES.DELETED_AT }, false);
    public static final Index IDX_SETTINGS_DELETED_AT = Internal.createIndex(DSL.name("idx_settings_deleted_at"), Settings.SETTINGS, new OrderField[] { Settings.SETTINGS.DELETED_AT }, false);
    public static final Index IDX_SHARES_DELETED_AT = Internal.createIndex(DSL.name("idx_shares_deleted_at"), Shares.SHARES, new OrderField[] { Shares.SHARES.DELETED_AT }, false);
    public static final Index IDX_TAGS_DELETED_AT = Internal.createIndex(DSL.name("idx_tags_deleted_at"), Tags.TAGS, new OrderField[] { Tags.TAGS.DELETED_AT }, false);
    public static final Index IDX_TASKS_DELETED_AT = Internal.createIndex(DSL.name("idx_tasks_deleted_at"), Tasks.TASKS, new OrderField[] { Tasks.TASKS.DELETED_AT }, false);
    public static final Index IDX_USERS_DELETED_AT = Internal.createIndex(DSL.name("idx_users_deleted_at"), Users.USERS, new OrderField[] { Users.USERS.DELETED_AT }, false);
    public static final Index IDX_WEBDAVS_DELETED_AT = Internal.createIndex(DSL.name("idx_webdavs_deleted_at"), Webdavs.WEBDAVS, new OrderField[] { Webdavs.WEBDAVS.DELETED_AT }, false);
    public static final Index OWNER_ID = Internal.createIndex(DSL.name("owner_id"), Folders.FOLDERS, new OrderField[] { Folders.FOLDERS.OWNER_ID }, false);
    public static final Index PARENT_ID = Internal.createIndex(DSL.name("parent_id"), Folders.FOLDERS, new OrderField[] { Folders.FOLDERS.PARENT_ID }, false);
    public static final Index PASSWORD_ONLY_ON = Internal.createIndex(DSL.name("password_only_on"), Webdavs.WEBDAVS, new OrderField[] { Webdavs.WEBDAVS.PASSWORD, Webdavs.WEBDAVS.USER_ID }, true);
    public static final Index SESSION_ID = Internal.createIndex(DSL.name("session_id"), Files.FILES, new OrderField[] { Files.FILES.UPLOAD_SESSION_ID }, false);
    public static final Index SESSION_ONLY_ONE = Internal.createIndex(DSL.name("session_only_one"), Files.FILES, new OrderField[] { Files.FILES.UPLOAD_SESSION_ID }, true);
    public static final Index SETTING_KEY = Internal.createIndex(DSL.name("setting_key"), Settings.SETTINGS, new OrderField[] { Settings.SETTINGS.NAME }, false);
    public static final Index SOURCE = Internal.createIndex(DSL.name("source"), Shares.SHARES, new OrderField[] { Shares.SHARES.SOURCE_NAME }, false);
    public static final Index UIX_USERS_EMAIL = Internal.createIndex(DSL.name("uix_users_email"), Users.USERS, new OrderField[] { Users.USERS.EMAIL }, true);
    public static final Index USER_ID = Internal.createIndex(DSL.name("user_id"), Files.FILES, new OrderField[] { Files.FILES.USER_ID }, false);
}
