/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Downloads;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Files;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Folders;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Groups;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Nodes;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Policies;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Settings;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Shares;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.SqliteSequence;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Tags;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Tasks;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Users;
import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Webdavs;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>downloads</code>.
     */
    public static final Downloads DOWNLOADS = Downloads.DOWNLOADS;

    /**
     * The table <code>files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>folders</code>.
     */
    public static final Folders FOLDERS = Folders.FOLDERS;

    /**
     * The table <code>groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>nodes</code>.
     */
    public static final Nodes NODES = Nodes.NODES;

    /**
     * The table <code>policies</code>.
     */
    public static final Policies POLICIES = Policies.POLICIES;

    /**
     * The table <code>settings</code>.
     */
    public static final Settings SETTINGS = Settings.SETTINGS;

    /**
     * The table <code>shares</code>.
     */
    public static final Shares SHARES = Shares.SHARES;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;

    /**
     * The table <code>tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>webdavs</code>.
     */
    public static final Webdavs WEBDAVS = Webdavs.WEBDAVS;
}
