/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.records;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Files;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilesRecord extends UpdatableRecordImpl<FilesRecord> implements Record13<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Integer, Integer, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>files.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>files.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>files.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>files.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>files.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>files.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>files.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>files.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>files.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>files.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>files.source_name</code>.
     */
    public void setSourceName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>files.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>files.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>files.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>files.size</code>.
     */
    public void setSize(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>files.size</code>.
     */
    public Long getSize() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>files.pic_info</code>.
     */
    public void setPicInfo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>files.pic_info</code>.
     */
    public String getPicInfo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>files.folder_id</code>.
     */
    public void setFolderId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>files.folder_id</code>.
     */
    public Integer getFolderId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>files.policy_id</code>.
     */
    public void setPolicyId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>files.policy_id</code>.
     */
    public Integer getPolicyId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>files.upload_session_id</code>.
     */
    public void setUploadSessionId(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>files.upload_session_id</code>.
     */
    public String getUploadSessionId() {
        return (String) get(11);
    }

    /**
     * Setter for <code>files.metadata</code>.
     */
    public void setMetadata(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>files.metadata</code>.
     */
    public String getMetadata() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Integer, Integer, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Integer, Long, String, Integer, Integer, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Files.FILES.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Files.FILES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Files.FILES.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Files.FILES.DELETED_AT;
    }

    @Override
    public Field<String> field5() {
        return Files.FILES.NAME;
    }

    @Override
    public Field<String> field6() {
        return Files.FILES.SOURCE_NAME;
    }

    @Override
    public Field<Integer> field7() {
        return Files.FILES.USER_ID;
    }

    @Override
    public Field<Long> field8() {
        return Files.FILES.SIZE;
    }

    @Override
    public Field<String> field9() {
        return Files.FILES.PIC_INFO;
    }

    @Override
    public Field<Integer> field10() {
        return Files.FILES.FOLDER_ID;
    }

    @Override
    public Field<Integer> field11() {
        return Files.FILES.POLICY_ID;
    }

    @Override
    public Field<String> field12() {
        return Files.FILES.UPLOAD_SESSION_ID;
    }

    @Override
    public Field<String> field13() {
        return Files.FILES.METADATA;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getSourceName();
    }

    @Override
    public Integer component7() {
        return getUserId();
    }

    @Override
    public Long component8() {
        return getSize();
    }

    @Override
    public String component9() {
        return getPicInfo();
    }

    @Override
    public Integer component10() {
        return getFolderId();
    }

    @Override
    public Integer component11() {
        return getPolicyId();
    }

    @Override
    public String component12() {
        return getUploadSessionId();
    }

    @Override
    public String component13() {
        return getMetadata();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getSourceName();
    }

    @Override
    public Integer value7() {
        return getUserId();
    }

    @Override
    public Long value8() {
        return getSize();
    }

    @Override
    public String value9() {
        return getPicInfo();
    }

    @Override
    public Integer value10() {
        return getFolderId();
    }

    @Override
    public Integer value11() {
        return getPolicyId();
    }

    @Override
    public String value12() {
        return getUploadSessionId();
    }

    @Override
    public String value13() {
        return getMetadata();
    }

    @Override
    public FilesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FilesRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FilesRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FilesRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FilesRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public FilesRecord value6(String value) {
        setSourceName(value);
        return this;
    }

    @Override
    public FilesRecord value7(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public FilesRecord value8(Long value) {
        setSize(value);
        return this;
    }

    @Override
    public FilesRecord value9(String value) {
        setPicInfo(value);
        return this;
    }

    @Override
    public FilesRecord value10(Integer value) {
        setFolderId(value);
        return this;
    }

    @Override
    public FilesRecord value11(Integer value) {
        setPolicyId(value);
        return this;
    }

    @Override
    public FilesRecord value12(String value) {
        setUploadSessionId(value);
        return this;
    }

    @Override
    public FilesRecord value13(String value) {
        setMetadata(value);
        return this;
    }

    @Override
    public FilesRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, Integer value7, Long value8, String value9, Integer value10, Integer value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FilesRecord
     */
    public FilesRecord() {
        super(Files.FILES);
    }

    /**
     * Create a detached, initialised FilesRecord
     */
    public FilesRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt, String name, String sourceName, Integer userId, Long size, String picInfo, Integer folderId, Integer policyId, String uploadSessionId, String metadata) {
        super(Files.FILES);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setName(name);
        setSourceName(sourceName);
        setUserId(userId);
        setSize(size);
        setPicInfo(picInfo);
        setFolderId(folderId);
        setPolicyId(policyId);
        setUploadSessionId(uploadSessionId);
        setMetadata(metadata);
    }
}
