/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.records;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Groups;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record11<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Long, Object, Object, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>groups.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>groups.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>groups.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>groups.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>groups.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>groups.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>groups.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>groups.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>groups.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>groups.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>groups.policies</code>.
     */
    public void setPolicies(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>groups.policies</code>.
     */
    public String getPolicies() {
        return (String) get(5);
    }

    /**
     * Setter for <code>groups.max_storage</code>.
     */
    public void setMaxStorage(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>groups.max_storage</code>.
     */
    public Long getMaxStorage() {
        return (Long) get(6);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setShareEnabled(Object value) {
        set(7, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getShareEnabled() {
        return get(7);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setWebDavEnabled(Object value) {
        set(8, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getWebDavEnabled() {
        return get(8);
    }

    /**
     * Setter for <code>groups.speed_limit</code>.
     */
    public void setSpeedLimit(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>groups.speed_limit</code>.
     */
    public Integer getSpeedLimit() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>groups.options</code>.
     */
    public void setOptions(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>groups.options</code>.
     */
    public String getOptions() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Long, Object, Object, Integer, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, Long, Object, Object, Integer, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Groups.GROUPS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Groups.GROUPS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Groups.GROUPS.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Groups.GROUPS.DELETED_AT;
    }

    @Override
    public Field<String> field5() {
        return Groups.GROUPS.NAME;
    }

    @Override
    public Field<String> field6() {
        return Groups.GROUPS.POLICIES;
    }

    @Override
    public Field<Long> field7() {
        return Groups.GROUPS.MAX_STORAGE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field8() {
        return Groups.GROUPS.SHARE_ENABLED;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field9() {
        return Groups.GROUPS.WEB_DAV_ENABLED;
    }

    @Override
    public Field<Integer> field10() {
        return Groups.GROUPS.SPEED_LIMIT;
    }

    @Override
    public Field<String> field11() {
        return Groups.GROUPS.OPTIONS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getPolicies();
    }

    @Override
    public Long component7() {
        return getMaxStorage();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component8() {
        return getShareEnabled();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component9() {
        return getWebDavEnabled();
    }

    @Override
    public Integer component10() {
        return getSpeedLimit();
    }

    @Override
    public String component11() {
        return getOptions();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getPolicies();
    }

    @Override
    public Long value7() {
        return getMaxStorage();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value8() {
        return getShareEnabled();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value9() {
        return getWebDavEnabled();
    }

    @Override
    public Integer value10() {
        return getSpeedLimit();
    }

    @Override
    public String value11() {
        return getOptions();
    }

    @Override
    public GroupsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public GroupsRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GroupsRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public GroupsRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public GroupsRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public GroupsRecord value6(String value) {
        setPolicies(value);
        return this;
    }

    @Override
    public GroupsRecord value7(Long value) {
        setMaxStorage(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public GroupsRecord value8(Object value) {
        setShareEnabled(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public GroupsRecord value9(Object value) {
        setWebDavEnabled(value);
        return this;
    }

    @Override
    public GroupsRecord value10(Integer value) {
        setSpeedLimit(value);
        return this;
    }

    @Override
    public GroupsRecord value11(String value) {
        setOptions(value);
        return this;
    }

    @Override
    public GroupsRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, Long value7, Object value8, Object value9, Integer value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt, String name, String policies, Long maxStorage, Object shareEnabled, Object webDavEnabled, Integer speedLimit, String options) {
        super(Groups.GROUPS);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setName(name);
        setPolicies(policies);
        setMaxStorage(maxStorage);
        setShareEnabled(shareEnabled);
        setWebDavEnabled(webDavEnabled);
        setSpeedLimit(speedLimit);
        setOptions(options);
    }
}
