/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.records;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Policies;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoliciesRecord extends UpdatableRecordImpl<PoliciesRecord> implements Record18<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, Object, String, String, String, Long, Object, String, String, Object, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>policies.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>policies.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>policies.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>policies.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>policies.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>policies.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>policies.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>policies.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>policies.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>policies.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>policies.type</code>.
     */
    public void setType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>policies.type</code>.
     */
    public String getType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>policies.server</code>.
     */
    public void setServer(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>policies.server</code>.
     */
    public String getServer() {
        return (String) get(6);
    }

    /**
     * Setter for <code>policies.bucket_name</code>.
     */
    public void setBucketName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>policies.bucket_name</code>.
     */
    public String getBucketName() {
        return (String) get(7);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setIsPrivate(Object value) {
        set(8, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getIsPrivate() {
        return get(8);
    }

    /**
     * Setter for <code>policies.base_url</code>.
     */
    public void setBaseUrl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>policies.base_url</code>.
     */
    public String getBaseUrl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>policies.access_key</code>.
     */
    public void setAccessKey(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>policies.access_key</code>.
     */
    public String getAccessKey() {
        return (String) get(10);
    }

    /**
     * Setter for <code>policies.secret_key</code>.
     */
    public void setSecretKey(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>policies.secret_key</code>.
     */
    public String getSecretKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>policies.max_size</code>.
     */
    public void setMaxSize(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>policies.max_size</code>.
     */
    public Long getMaxSize() {
        return (Long) get(12);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setAutoRename(Object value) {
        set(13, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getAutoRename() {
        return get(13);
    }

    /**
     * Setter for <code>policies.dir_name_rule</code>.
     */
    public void setDirNameRule(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>policies.dir_name_rule</code>.
     */
    public String getDirNameRule() {
        return (String) get(14);
    }

    /**
     * Setter for <code>policies.file_name_rule</code>.
     */
    public void setFileNameRule(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>policies.file_name_rule</code>.
     */
    public String getFileNameRule() {
        return (String) get(15);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public void setIsOriginLinkEnable(Object value) {
        set(16, value);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    public Object getIsOriginLinkEnable() {
        return get(16);
    }

    /**
     * Setter for <code>policies.options</code>.
     */
    public void setOptions(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>policies.options</code>.
     */
    public String getOptions() {
        return (String) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, Object, String, String, String, Long, Object, String, String, Object, String> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, String, Object, String, String, String, Long, Object, String, String, Object, String> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Policies.POLICIES.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Policies.POLICIES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Policies.POLICIES.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Policies.POLICIES.DELETED_AT;
    }

    @Override
    public Field<String> field5() {
        return Policies.POLICIES.NAME;
    }

    @Override
    public Field<String> field6() {
        return Policies.POLICIES.TYPE;
    }

    @Override
    public Field<String> field7() {
        return Policies.POLICIES.SERVER;
    }

    @Override
    public Field<String> field8() {
        return Policies.POLICIES.BUCKET_NAME;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field9() {
        return Policies.POLICIES.IS_PRIVATE;
    }

    @Override
    public Field<String> field10() {
        return Policies.POLICIES.BASE_URL;
    }

    @Override
    public Field<String> field11() {
        return Policies.POLICIES.ACCESS_KEY;
    }

    @Override
    public Field<String> field12() {
        return Policies.POLICIES.SECRET_KEY;
    }

    @Override
    public Field<Long> field13() {
        return Policies.POLICIES.MAX_SIZE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field14() {
        return Policies.POLICIES.AUTO_RENAME;
    }

    @Override
    public Field<String> field15() {
        return Policies.POLICIES.DIR_NAME_RULE;
    }

    @Override
    public Field<String> field16() {
        return Policies.POLICIES.FILE_NAME_RULE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Field<Object> field17() {
        return Policies.POLICIES.IS_ORIGIN_LINK_ENABLE;
    }

    @Override
    public Field<String> field18() {
        return Policies.POLICIES.OPTIONS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getType();
    }

    @Override
    public String component7() {
        return getServer();
    }

    @Override
    public String component8() {
        return getBucketName();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component9() {
        return getIsPrivate();
    }

    @Override
    public String component10() {
        return getBaseUrl();
    }

    @Override
    public String component11() {
        return getAccessKey();
    }

    @Override
    public String component12() {
        return getSecretKey();
    }

    @Override
    public Long component13() {
        return getMaxSize();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component14() {
        return getAutoRename();
    }

    @Override
    public String component15() {
        return getDirNameRule();
    }

    @Override
    public String component16() {
        return getFileNameRule();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object component17() {
        return getIsOriginLinkEnable();
    }

    @Override
    public String component18() {
        return getOptions();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getType();
    }

    @Override
    public String value7() {
        return getServer();
    }

    @Override
    public String value8() {
        return getBucketName();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value9() {
        return getIsPrivate();
    }

    @Override
    public String value10() {
        return getBaseUrl();
    }

    @Override
    public String value11() {
        return getAccessKey();
    }

    @Override
    public String value12() {
        return getSecretKey();
    }

    @Override
    public Long value13() {
        return getMaxSize();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value14() {
        return getAutoRename();
    }

    @Override
    public String value15() {
        return getDirNameRule();
    }

    @Override
    public String value16() {
        return getFileNameRule();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public Object value17() {
        return getIsOriginLinkEnable();
    }

    @Override
    public String value18() {
        return getOptions();
    }

    @Override
    public PoliciesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PoliciesRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public PoliciesRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public PoliciesRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public PoliciesRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public PoliciesRecord value6(String value) {
        setType(value);
        return this;
    }

    @Override
    public PoliciesRecord value7(String value) {
        setServer(value);
        return this;
    }

    @Override
    public PoliciesRecord value8(String value) {
        setBucketName(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public PoliciesRecord value9(Object value) {
        setIsPrivate(value);
        return this;
    }

    @Override
    public PoliciesRecord value10(String value) {
        setBaseUrl(value);
        return this;
    }

    @Override
    public PoliciesRecord value11(String value) {
        setAccessKey(value);
        return this;
    }

    @Override
    public PoliciesRecord value12(String value) {
        setSecretKey(value);
        return this;
    }

    @Override
    public PoliciesRecord value13(Long value) {
        setMaxSize(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public PoliciesRecord value14(Object value) {
        setAutoRename(value);
        return this;
    }

    @Override
    public PoliciesRecord value15(String value) {
        setDirNameRule(value);
        return this;
    }

    @Override
    public PoliciesRecord value16(String value) {
        setFileNameRule(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @Deprecated
    @Override
    public PoliciesRecord value17(Object value) {
        setIsOriginLinkEnable(value);
        return this;
    }

    @Override
    public PoliciesRecord value18(String value) {
        setOptions(value);
        return this;
    }

    @Override
    public PoliciesRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, String value7, String value8, Object value9, String value10, String value11, String value12, Long value13, Object value14, String value15, String value16, Object value17, String value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PoliciesRecord
     */
    public PoliciesRecord() {
        super(Policies.POLICIES);
    }

    /**
     * Create a detached, initialised PoliciesRecord
     */
    public PoliciesRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt, String name, String type, String server, String bucketName, Object isPrivate, String baseUrl, String accessKey, String secretKey, Long maxSize, Object autoRename, String dirNameRule, String fileNameRule, Object isOriginLinkEnable, String options) {
        super(Policies.POLICIES);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setName(name);
        setType(type);
        setServer(server);
        setBucketName(bucketName);
        setIsPrivate(isPrivate);
        setBaseUrl(baseUrl);
        setAccessKey(accessKey);
        setSecretKey(secretKey);
        setMaxSize(maxSize);
        setAutoRename(autoRename);
        setDirNameRule(dirNameRule);
        setFileNameRule(fileNameRule);
        setIsOriginLinkEnable(isOriginLinkEnable);
        setOptions(options);
    }
}
