/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.records;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Tags;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsRecord extends UpdatableRecordImpl<TagsRecord> implements Record10<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>tags.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tags.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tags.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>tags.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>tags.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>tags.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>tags.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>tags.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>tags.name</code>.
     */
    public void setName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tags.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tags.icon</code>.
     */
    public void setIcon(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tags.icon</code>.
     */
    public String getIcon() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tags.color</code>.
     */
    public void setColor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tags.color</code>.
     */
    public String getColor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tags.type</code>.
     */
    public void setType(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>tags.type</code>.
     */
    public Integer getType() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>tags.expression</code>.
     */
    public void setExpression(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>tags.expression</code>.
     */
    public String getExpression() {
        return (String) get(8);
    }

    /**
     * Setter for <code>tags.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>tags.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, String, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Tags.TAGS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Tags.TAGS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Tags.TAGS.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Tags.TAGS.DELETED_AT;
    }

    @Override
    public Field<String> field5() {
        return Tags.TAGS.NAME;
    }

    @Override
    public Field<String> field6() {
        return Tags.TAGS.ICON;
    }

    @Override
    public Field<String> field7() {
        return Tags.TAGS.COLOR;
    }

    @Override
    public Field<Integer> field8() {
        return Tags.TAGS.TYPE;
    }

    @Override
    public Field<String> field9() {
        return Tags.TAGS.EXPRESSION;
    }

    @Override
    public Field<Integer> field10() {
        return Tags.TAGS.USER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public String component6() {
        return getIcon();
    }

    @Override
    public String component7() {
        return getColor();
    }

    @Override
    public Integer component8() {
        return getType();
    }

    @Override
    public String component9() {
        return getExpression();
    }

    @Override
    public Integer component10() {
        return getUserId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public String value6() {
        return getIcon();
    }

    @Override
    public String value7() {
        return getColor();
    }

    @Override
    public Integer value8() {
        return getType();
    }

    @Override
    public String value9() {
        return getExpression();
    }

    @Override
    public Integer value10() {
        return getUserId();
    }

    @Override
    public TagsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TagsRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public TagsRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public TagsRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public TagsRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public TagsRecord value6(String value) {
        setIcon(value);
        return this;
    }

    @Override
    public TagsRecord value7(String value) {
        setColor(value);
        return this;
    }

    @Override
    public TagsRecord value8(Integer value) {
        setType(value);
        return this;
    }

    @Override
    public TagsRecord value9(String value) {
        setExpression(value);
        return this;
    }

    @Override
    public TagsRecord value10(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TagsRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, String value7, Integer value8, String value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsRecord
     */
    public TagsRecord() {
        super(Tags.TAGS);
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt, String name, String icon, String color, Integer type, String expression, Integer userId) {
        super(Tags.TAGS);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setName(name);
        setIcon(icon);
        setColor(color);
        setType(type);
        setExpression(expression);
        setUserId(userId);
    }
}
