/*
 * This file is generated by jOOQ.
 */
package com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.records;


import com.tuzhihao.cloudreve.helper.cloudrevehelper.repository.tables.Users;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record14<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, Integer, Long, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>users.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>users.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>users.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>users.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>users.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>users.nick</code>.
     */
    public void setNick(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>users.nick</code>.
     */
    public String getNick() {
        return (String) get(5);
    }

    /**
     * Setter for <code>users.password</code>.
     */
    public void setPassword(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>users.password</code>.
     */
    public String getPassword() {
        return (String) get(6);
    }

    /**
     * Setter for <code>users.status</code>.
     */
    public void setStatus(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>users.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>users.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>users.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>users.storage</code>.
     */
    public void setStorage(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>users.storage</code>.
     */
    public Long getStorage() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>users.two_factor</code>.
     */
    public void setTwoFactor(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>users.two_factor</code>.
     */
    public String getTwoFactor() {
        return (String) get(10);
    }

    /**
     * Setter for <code>users.avatar</code>.
     */
    public void setAvatar(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>users.avatar</code>.
     */
    public String getAvatar() {
        return (String) get(11);
    }

    /**
     * Setter for <code>users.options</code>.
     */
    public void setOptions(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>users.options</code>.
     */
    public String getOptions() {
        return (String) get(12);
    }

    /**
     * Setter for <code>users.authn</code>.
     */
    public void setAuthn(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>users.authn</code>.
     */
    public String getAuthn() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row14<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, Integer, Long, String, String, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    @Override
    public Row14<Integer, LocalDateTime, LocalDateTime, LocalDateTime, String, String, String, Integer, Integer, Long, String, String, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<LocalDateTime> field2() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Users.USERS.UPDATED_AT;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Users.USERS.DELETED_AT;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.EMAIL;
    }

    @Override
    public Field<String> field6() {
        return Users.USERS.NICK;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<Integer> field8() {
        return Users.USERS.STATUS;
    }

    @Override
    public Field<Integer> field9() {
        return Users.USERS.GROUP_ID;
    }

    @Override
    public Field<Long> field10() {
        return Users.USERS.STORAGE;
    }

    @Override
    public Field<String> field11() {
        return Users.USERS.TWO_FACTOR;
    }

    @Override
    public Field<String> field12() {
        return Users.USERS.AVATAR;
    }

    @Override
    public Field<String> field13() {
        return Users.USERS.OPTIONS;
    }

    @Override
    public Field<String> field14() {
        return Users.USERS.AUTHN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDateTime component2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime component4() {
        return getDeletedAt();
    }

    @Override
    public String component5() {
        return getEmail();
    }

    @Override
    public String component6() {
        return getNick();
    }

    @Override
    public String component7() {
        return getPassword();
    }

    @Override
    public Integer component8() {
        return getStatus();
    }

    @Override
    public Integer component9() {
        return getGroupId();
    }

    @Override
    public Long component10() {
        return getStorage();
    }

    @Override
    public String component11() {
        return getTwoFactor();
    }

    @Override
    public String component12() {
        return getAvatar();
    }

    @Override
    public String component13() {
        return getOptions();
    }

    @Override
    public String component14() {
        return getAuthn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDateTime value2() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value3() {
        return getUpdatedAt();
    }

    @Override
    public LocalDateTime value4() {
        return getDeletedAt();
    }

    @Override
    public String value5() {
        return getEmail();
    }

    @Override
    public String value6() {
        return getNick();
    }

    @Override
    public String value7() {
        return getPassword();
    }

    @Override
    public Integer value8() {
        return getStatus();
    }

    @Override
    public Integer value9() {
        return getGroupId();
    }

    @Override
    public Long value10() {
        return getStorage();
    }

    @Override
    public String value11() {
        return getTwoFactor();
    }

    @Override
    public String value12() {
        return getAvatar();
    }

    @Override
    public String value13() {
        return getOptions();
    }

    @Override
    public String value14() {
        return getAuthn();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value3(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UsersRecord value4(LocalDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UsersRecord value6(String value) {
        setNick(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value8(Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    public UsersRecord value9(Integer value) {
        setGroupId(value);
        return this;
    }

    @Override
    public UsersRecord value10(Long value) {
        setStorage(value);
        return this;
    }

    @Override
    public UsersRecord value11(String value) {
        setTwoFactor(value);
        return this;
    }

    @Override
    public UsersRecord value12(String value) {
        setAvatar(value);
        return this;
    }

    @Override
    public UsersRecord value13(String value) {
        setOptions(value);
        return this;
    }

    @Override
    public UsersRecord value14(String value) {
        setAuthn(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, LocalDateTime value2, LocalDateTime value3, LocalDateTime value4, String value5, String value6, String value7, Integer value8, Integer value9, Long value10, String value11, String value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime deletedAt, String email, String nick, String password, Integer status, Integer groupId, Long storage, String twoFactor, String avatar, String options, String authn) {
        super(Users.USERS);

        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setEmail(email);
        setNick(nick);
        setPassword(password);
        setStatus(status);
        setGroupId(groupId);
        setStorage(storage);
        setTwoFactor(twoFactor);
        setAvatar(avatar);
        setOptions(options);
        setAuthn(authn);
    }
}
